language: python
addons:
  apt:
    packages:
    - verilator
python:
    - "3.6"

install:
    - pip install python-coveralls
    - pip install pytest-cov pytest-pep8
    - pip install -r requirements.txt
    - pip install -e .

script:
    - pytest --cov fault --pep8 fault -v --cov-report term-missing tests

after_success:
    - coveralls
