language: python
addons:
  apt:
    packages:
    - verilator
# python managed by conda until 3.7 available
# python:
# - '3.6'
before_install:
- sudo add-apt-repository -y ppa:team-electronics/ppa
- sudo apt-get update
- sudo apt-get install iverilog-daily

install:
# install conda for py 3.7
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
- export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-env python=3.7
- source activate test-env
- conda install pip
# End install conda
- pip install python-coveralls
- pip install pytest-cov pytest-codestyle
- pip install mantle  # for tests.common
- pip install -e .
# Begin setup CoSA dependencies
- pysmt-install --msat --confirm-agreement
- pysmt-install --z3 --confirm-agreement
- export PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.6:${PYTHONPATH}"
- export LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.6:${LD_LIBRARY_PATH}"
# - pysmt-install --check
# End setup CoSA dependencies

script:
- pytest --cov fault --codestyle fault -v --cov-report term-missing tests
after_success:
- coveralls
deploy:
  provider: script
  script: /bin/bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
