language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - verilator
python:
- '3.6'
install:
- wget https://raw.githubusercontent.com/phanrahan/magma/master/.travis/install_coreir.sh
- source install_coreir.sh
- pip install python-coveralls
- pip install pytest-cov pytest-pep8
- pip install -r requirements.txt
- pip install -e .
script:
- pytest --cov fault --pep8 fault -v --cov-report term-missing tests
after_success:
- coveralls
deploy:
  provider: pypi
  user: leonardt
  password:
    secure: YHAk4AFTk1yXCI0AJz8+VQ1L2+Cm2+8Z41jSw5d+kgzMrlyDhmqGcdei63fLzeZgjxkhCeMhr3aHFdcCXPvH/otWKnPPEjRh3ug6vCs6XUoo1n7G8GsMCAsSExws68X26eLSmHjXRjYEkDIHONaL3XUfL/qknYDyN2jZasCEvzE1fU8AUIclOziLuKaHUKZwJ8u1T4ptH0fkOTuFWNhQ+/n2LBeurgsLBiJCjBpUn/tTaPa6FQN8zvQ0tvcnDWT5PQAqAk+h4EFmoA2IXSADOdn41WTG/0IrzDviSMiotX9tl9xt+1j6RAKXF5W0ZvkwDh/7A8ImlgdCRFn9wQutCDsnDWQssZHRo+ymjdVC+G/90UAWbV5C59vjh6R6ModJwTqyWVc4GuTFpX+aG5M5aBqPnJju6bFA/wqJTmYnsxz2eSYMDwFTJwWVD22rs2xJY71iZvxI0WmiKbIyvxr3ZmkUYAtq7XMUvzawDI+OjuamSYJUU26nLA3eY4uIbxPkPe4A7V3yhnxI0O66jXokgyxiOsCSyiTI25GzHCoi7fGcC27LYfwP646LrcROCkz20pP53Qhv9O6cDk+i7BWqwcEAOANzA1gesZtkhdVNu0o6vaRJNC/5wby/tj5fjCZSlbiFt8gy5kmNu34H/1err1j9kS3SzUya/mFkX0Dvxig=
  on:
    tags: true
    branch: master
