language: python
python:
- '3.6'
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libgmp-dev
        - libmpfr-dev
        - libmpc-dev
        - verilator
    env:
    - CC=gcc-7
    - CXX=g++-7
  - os: osx
    osx_image: xcode10.2

install:
- curl -s -L https://github.com/rdaly525/coreir/releases/latest | grep "href.*coreir-${TRAVIS_OS_NAME}.tar.gz" | cut -d \" -f 2 | xargs -I {} wget https://github.com"{}"
- mkdir coreir_release;
- tar -xf coreir-${TRAVIS_OS_NAME}.tar.gz -C coreir_release --strip-components 1;
- cd coreir_release && sudo make install && cd ..
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # avoid strange libjpeg error (see https://github.com/sgrif/pq-sys/issues/1
    # for some more info)
    export DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/:/usr/local/lib:$DYLD_LIBRARY_PATH
  fi
- pip install pytest-cov pytest-codestyle
- pip install mantle  # for tests.common
- pip install -e .
# Begin setup CoSA dependencies
- pysmt-install --msat --confirm-agreement
- pysmt-install --z3 --confirm-agreement
- export PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.7:${PYTHONPATH}"
- export LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.7:${LD_LIBRARY_PATH}"
- pysmt-install --check
# End setup CoSA dependencies

script:
- pytest --cov fault --codestyle fault -v --cov-report term-missing tests
deploy:
  provider: script
  script: /bin/bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
